// Generated by bun-plugin-auto-imports

export { increment, decrement, reset, count } from '../../../resources/functions/counter'
export { toggleDark, isDark, preferredDark } from '../../../resources/functions/dark'
