-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "accounts" ADD COLUMN "auto_delete_enabled" INTEGER default 0;
ALTER TABLE "accounts" ADD COLUMN "auto_delete_days" INTEGER default 7;
ALTER TABLE "accounts" ADD COLUMN "auto_delete_providers" TEXT default '[]';
ALTER TABLE "accounts" ADD COLUMN "auto_delete_scope" TEXT CHECK ("auto_delete_scope" IN ('tracked', 'all')) default 'all';
